# roles/systemd_unit/vars/main.yml
# ================================
#
# Copying
# -------
#
# Copyright (c) 2026 universe.unix authors and contributors.
#
# This file is part of the *universe.unix* project.
#
# *universe.unix* is a free software project. You can redistribute it
# and/or modify it following the terms of the MIT License.
#
# This software project is distributed *as is*, WITHOUT WARRANTY OF ANY KIND;
# including but not limited to the WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE and NONINFRINGEMENT.
#
# You should have received a copy of the MIT License along with
# *universe.unix*. If not, see <http://opensource.org/licenses/MIT>.
#
_systemd_unit_scope_default: "system"

systemd_unit_scope_owner: >-
  {{ systemd_unit_scope == 'user' | ternary(ansible_facts.user_id, 'root') }}

systemd_unit_scope_path:
  global: "{{ dirs_prefix }}/lib/systemd/user"
  system: "{{ dirs_prefix }}/lib/systemd/system"
  user: "{{ dirs_xdg_data_home }}/systemd/user"

systemd_unit_scope_setype:
  global: "systemd_unit_file_t"
  system: "systemd_unit_file_t"
  user: "data_home_t"
