# .pymarkdown.yml
# ===============
#
# Copying
# -------
#
# Copyright (c) 2022 universe.unix authors and contributors.
#
# This file is part of the *universe.unix* project.
#
# *universe.unix* is a free software project. You can redistribute it and/or
# modify it following the terms of the MIT License.
#
# This software project is distributed *as is*, WITHOUT WARRANTY OF ANY KIND;
# including but not limited to the WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE and NONINFRINGEMENT.
#
# You should have received a copy of the MIT License along with
# *universe.unix*. If not, see <http://opensource.org/licenses/MIT>.
#
plugins:
  # MD003: Heading style should be consistent throughout the document.
  md003:
    enabled: true
    style: "setext_with_atx"
  # MD041: First line in file should be a top-level heading.
  md041:
    enabled: false
