# galaxy.yml
# ==========
#
# Copying
# -------
#
# Copyright (c) 2022 universe.unix authors and contributors.
#
# This file is part of the *universe.unix* project.
#
# *universe.unix* is a free software project. You can redistribute it and/or
# modify it following the terms of the MIT License.
#
# This software project is distributed *as is*, WITHOUT WARRANTY OF ANY KIND;
# including but not limited to the WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE and NONINFRINGEMENT.
#
# You should have received a copy of the MIT License along with
# *universe.unix*. If not, see <http://opensource.org/licenses/MIT>.
#
namespace: "universe"
name: "unix"
description: "A set of Ansible modules targeting Unix-like systems."
version: "0.1.0-alpha.1"
readme: "README.md"
authors:
  - "See AUTHORS.rst"
license_file: "LICENSE.rst"
tags:
  - "linux"
  - "posix"
  - "unix"
dependencies:
  "community.general": ">=1.6.0"
  "universe.common": ">=0.1.0"
repository: "https://github.com/x237net/ansible-universe-unix"
issues: "https://github.com/x237net/ansible-universe-unix/issues"
build_ignore:
  - ".editorconfig"
  - ".gitignore"
  - ".pre-commit-config.yaml"
