# roles/gpg_import/tasks/import.yml
# =================================
#
# Copying
# -------
#
# Copyright (c) 2023 universe.unix authors and contributors.
#
# This file is part of the *universe.unix* project.
#
# *universe.unix* is a free software project. You can redistribute it and/or
# modify it following the terms of the MIT License.
#
# This software project is distributed *as is*, WITHOUT WARRANTY OF ANY KIND;
# including but not limited to the WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE and NONINFRINGEMENT.
#
# You should have received a copy of the MIT License along with
# *universe.unix*. If not, see <http://opensource.org/licenses/MIT>.
#
- block:
  - name: "Create temporary ASC file"
    ansible.builtin.tempfile:
      state: "file"
      suffix: ".asc"
    register: "_gpg_tmp_asc"

  - name: "Write ASC file content"
    ansible.builtin.blockinfile:
      state: "present"
      path: "{{ _gpg_tmp_asc.path }}"
      block: "{{ gpg_import_content }}"
      marker: ""

  - name: "Import GPG key"
    ansible.builtin.command:
      cmd: "gpg --import {{ _gpg_tmp_asc.path }}"

  - ansible.builtin.debug:
      msg: "Cleanup"
    notify: "gpg-import-cleanup"
    changed_when: true
  rescue:
    - ansible.builtin.debug:
        msg: "Cleanup"
      notify: "gpg-import-cleanup"
      changed_when: true
  when: "gpg_import_content is defined"
