# roles/gpg_import/tasks/import.yml
# =================================
#
# Copying
# -------
#
# Copyright (c) 2023 universe.unix authors and contributors.
#
# This file is part of the *universe.unix* project.
#
# *universe.unix* is a free software project. You can redistribute it and/or
# modify it following the terms of the MIT License.
#
# This software project is distributed *as is*, WITHOUT WARRANTY OF ANY KIND;
# including but not limited to the WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE and NONINFRINGEMENT.
#
# You should have received a copy of the MIT License along with
# *universe.unix*. If not, see <http://opensource.org/licenses/MIT>.
#
- name: "Import GPG key"
  when: "gpg_import_content is defined"
  block:
    - name: "Create temporary ASC file"
      ansible.builtin.tempfile:
        state: "file"
        suffix: ".asc"
      register: "_gpg_tmp_asc"

    - name: "Write ASC file content"
      ansible.builtin.blockinfile:
        state: "present"
        path: "{{ _gpg_tmp_asc.path }}"
        block: "{{ gpg_import_content }}"
        marker: ""

    - name: "Call GPG import"
      ansible.builtin.command:
        cmd: "gpg --textmode --import {{ _gpg_tmp_asc.path }}"
      register: "_out"
      changed_when: "_out.stderr_lines | select('search', 'imported: 1') | list"

    - name: "Perform cleanup"
      ansible.builtin.debug:
        msg: "Cleanup"
      notify: "gpg-import-cleanup"
      changed_when: true
  rescue:
    - name: "Perform cleanup"
      ansible.builtin.debug:
        msg: "Cleanup"
      notify: "gpg-import-cleanup"
      changed_when: true
