# roles/package_install_utils/vars/main.yml
# =========================================
#
# Copying
# -------
#
# Copyright (c) 2023 universe.unix authors and contributors.
#
# This file is part of the *universe.unix* project.
#
# *universe.unix* is a free software project. You can redistribute it and/or
# modify it following the terms of the MIT License.
#
# This software project is distributed *as is*, WITHOUT WARRANTY OF ANY KIND;
# including but not limited to the WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE and NONINFRINGEMENT.
#
# You should have received a copy of the MIT License along with
# *universe.unix*. If not, see <http://opensource.org/licenses/MIT>.
#
package_install_utils_redhat:
  - "bc"
  - "binutils"
  - "diffutils"
  - "dos2unix"
  - "file"
  - "findutils"
  - "gnupg2"
  - "iotop"
  - "jq"
  - "lsof"
  - "patchutils"
  - "symlinks"
  - "tmux"
  - "tree"
  - "unzip"
  - "which"
  - "xz"
  - "zip"

package_install_utils_fedora:
  - "htop"

package_install_utils_family:
  fedora: >-
    {{
      package_install_utils_redhat
      | default([])
      | union(package_install_utils_fedora)
    }}
  redhat: "{{ package_install_utils_redhat }}"

package_install_utils_install: >-
  {{
    package_install_utils_family | universe.common.get(
      ansible_facts.distribution | lower,
      ansible_facts.os_family | lower
    )
  }}
