# roles/sudo_exec/tasks/main.yml
# ==============================
#
# Copying
# -------
#
# Copyright (c) 2023 universe.unix authors and contributors.
#
# This file is part of the *universe.unix* project.
#
# *universe.unix* is a free software project. You can redistribute it and/or
# modify it following the terms of the MIT License.
#
# This software project is distributed *as is*, WITHOUT WARRANTY OF ANY KIND;
# including but not limited to the WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE and NONINFRINGEMENT.
#
# You should have received a copy of the MIT License along with
# *universe.unix*. If not, see <http://opensource.org/licenses/MIT>.
#
- name: "Ensure presence of the sudo execution group"
  ansible.builtin.group:
    state: "present"
    name: "{{ sudo_exec_group }}"
    system: true

- name: "Add user to the sudo execution group"
  ansible.builtin.user:
    state: "present"
    name: "{{ sudo_exec_user }}"
    append: true
    groups:
      - "{{ sudo_exec_group }}"
  when: "sudo_exec_user is string"

- name: "Add user to the sudo execution group"
  ansible.builtin.user:
    state: "present"
    name: "{{ item }}"
    append: true
    groups:
      - "{{ sudo_exec_group }}"
  loop : "{{ sudo_exec_user | list }}"
  when: "sudo_exec_user is not string and sudo_exec_user is iterable"

- name: "Set sudo binary permissions"
  ansible.builtin.file:
    state: "file"
    path: "{{ sudo_exec_bin }}"
    follow: false
    mode: "4110"
    owner: "root"
    group: "{{ sudo_exec_group }}"
